// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban-card-attachment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKanbanAttachment = `-- name: CreateKanbanAttachment :one
INSERT INTO card_attachments (card_id, filename, file_type, file_size_bytes, attachment_data, uploaded_by, uploaded_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING attachment_id, card_id, filename, file_type, file_size_bytes, attachment_data, uploaded_at, uploaded_by
`

type CreateKanbanAttachmentParams struct {
	CardID         int32
	Filename       string
	FileType       pgtype.Text
	FileSizeBytes  pgtype.Int8
	AttachmentData []byte
	UploadedBy     string
	UploadedAt     pgtype.Timestamptz
}

func (q *Queries) CreateKanbanAttachment(ctx context.Context, arg CreateKanbanAttachmentParams) (CardAttachment, error) {
	row := q.db.QueryRow(ctx, createKanbanAttachment,
		arg.CardID,
		arg.Filename,
		arg.FileType,
		arg.FileSizeBytes,
		arg.AttachmentData,
		arg.UploadedBy,
		arg.UploadedAt,
	)
	var i CardAttachment
	err := row.Scan(
		&i.AttachmentID,
		&i.CardID,
		&i.Filename,
		&i.FileType,
		&i.FileSizeBytes,
		&i.AttachmentData,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const deleteAllKanbanAttachments = `-- name: DeleteAllKanbanAttachments :exec
DELETE FROM card_attachments
`

func (q *Queries) DeleteAllKanbanAttachments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllKanbanAttachments)
	return err
}

const deleteKanbanAttachment = `-- name: DeleteKanbanAttachment :exec
DELETE FROM card_attachments WHERE attachment_id = $1
`

func (q *Queries) DeleteKanbanAttachment(ctx context.Context, attachmentID int32) error {
	_, err := q.db.Exec(ctx, deleteKanbanAttachment, attachmentID)
	return err
}

const deleteKanbanAttachmentsForCard = `-- name: DeleteKanbanAttachmentsForCard :exec
DELETE FROM card_attachments WHERE card_id = $1
`

func (q *Queries) DeleteKanbanAttachmentsForCard(ctx context.Context, cardID int32) error {
	_, err := q.db.Exec(ctx, deleteKanbanAttachmentsForCard, cardID)
	return err
}

const getKanbanAttachmentById = `-- name: GetKanbanAttachmentById :one
SELECT attachment_id, card_id, filename, file_type, file_size_bytes, attachment_data, uploaded_at, uploaded_by FROM card_attachments WHERE attachment_id = $1
`

func (q *Queries) GetKanbanAttachmentById(ctx context.Context, attachmentID int32) (CardAttachment, error) {
	row := q.db.QueryRow(ctx, getKanbanAttachmentById, attachmentID)
	var i CardAttachment
	err := row.Scan(
		&i.AttachmentID,
		&i.CardID,
		&i.Filename,
		&i.FileType,
		&i.FileSizeBytes,
		&i.AttachmentData,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const getKanbanCardAttachments = `-- name: GetKanbanCardAttachments :many
SELECT attachment_id, card_id, filename, file_type, file_size_bytes, attachment_data, uploaded_at, uploaded_by FROM card_attachments WHERE card_id = $1
`

func (q *Queries) GetKanbanCardAttachments(ctx context.Context, cardID int32) ([]CardAttachment, error) {
	rows, err := q.db.Query(ctx, getKanbanCardAttachments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardAttachment
	for rows.Next() {
		var i CardAttachment
		if err := rows.Scan(
			&i.AttachmentID,
			&i.CardID,
			&i.Filename,
			&i.FileType,
			&i.FileSizeBytes,
			&i.AttachmentData,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
