// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban-card.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCardDependencies = `-- name: CreateCardDependencies :execresult
INSERT INTO card_dependencies (card_id, depends_on_card_id)
SELECT $1 as card_id, unnest($2::int[]) as dependency_card_id
`

type CreateCardDependenciesParams struct {
	CardID  int32
	Column2 []int32
}

// Purpose: Establish multiple dependency relationships for one card in a single statement.
// Parameters: $1 = card_id (int), $2 = depends_on_card_id (int[])
func (q *Queries) CreateCardDependencies(ctx context.Context, arg CreateCardDependenciesParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createCardDependencies, arg.CardID, arg.Column2)
}

const createCardDependency = `-- name: CreateCardDependency :execresult
INSERT INTO card_dependencies (card_id, depends_on_card_id) VALUES ($1, $2)
`

type CreateCardDependencyParams struct {
	CardID          int32
	DependsOnCardID int32
}

// Purpose: Establish a dependency relationship between two cards.
// Parameters: $1 = card_id, $2 = depends_on_card_id
func (q *Queries) CreateCardDependency(ctx context.Context, arg CreateCardDependencyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createCardDependency, arg.CardID, arg.DependsOnCardID)
}

const createKanbanCard = `-- name: CreateKanbanCard :one
INSERT INTO kanban_cards (board_id, title, description, status, assignee, story_points, acceptance_criteria, time_spent_hours,
 created_by, priority, type, is_blocked, blocked_reason) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING card_id, board_id, title, description, status, assignee, story_points, acceptance_criteria, time_spent_hours, created_at, created_by, updated_at, updated_by, priority, type, is_blocked, blocked_reason
`

type CreateKanbanCardParams struct {
	BoardID            int32
	Title              string
	Description        pgtype.Text
	Status             string
	Assignee           pgtype.Text
	StoryPoints        pgtype.Int2
	AcceptanceCriteria pgtype.Text
	TimeSpentHours     pgtype.Numeric
	CreatedBy          string
	Priority           pgtype.Text
	Type               pgtype.Text
	IsBlocked          pgtype.Bool
	BlockedReason      pgtype.Text
}

func (q *Queries) CreateKanbanCard(ctx context.Context, arg CreateKanbanCardParams) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, createKanbanCard,
		arg.BoardID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Assignee,
		arg.StoryPoints,
		arg.AcceptanceCriteria,
		arg.TimeSpentHours,
		arg.CreatedBy,
		arg.Priority,
		arg.Type,
		arg.IsBlocked,
		arg.BlockedReason,
	)
	var i KanbanCard
	err := row.Scan(
		&i.CardID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Assignee,
		&i.StoryPoints,
		&i.AcceptanceCriteria,
		&i.TimeSpentHours,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Priority,
		&i.Type,
		&i.IsBlocked,
		&i.BlockedReason,
	)
	return i, err
}

const deleteAllKanbanCards = `-- name: DeleteAllKanbanCards :exec
DELETE FROM kanban_cards
`

func (q *Queries) DeleteAllKanbanCards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllKanbanCards)
	return err
}

const deleteCardDependencies = `-- name: DeleteCardDependencies :exec
DELETE FROM card_dependencies WHERE card_id = $1
`

// Purpose: Remove all dependency relationships for provided card.
// Parameters: $1 = card_id
func (q *Queries) DeleteCardDependencies(ctx context.Context, cardID int32) error {
	_, err := q.db.Exec(ctx, deleteCardDependencies, cardID)
	return err
}

const deleteCardDependency = `-- name: DeleteCardDependency :exec
DELETE FROM card_dependencies WHERE card_id = $1 AND depends_on_card_id = $2
`

type DeleteCardDependencyParams struct {
	CardID          int32
	DependsOnCardID int32
}

// Purpose: Remove a specific dependency relationship between two cards.
// Parameters: $1 = card_id, $2 = depends_on_card_id
func (q *Queries) DeleteCardDependency(ctx context.Context, arg DeleteCardDependencyParams) error {
	_, err := q.db.Exec(ctx, deleteCardDependency, arg.CardID, arg.DependsOnCardID)
	return err
}

const deleteKanbanCard = `-- name: DeleteKanbanCard :exec
DELETE FROM kanban_cards WHERE card_id = $1
`

func (q *Queries) DeleteKanbanCard(ctx context.Context, cardID int32) error {
	_, err := q.db.Exec(ctx, deleteKanbanCard, cardID)
	return err
}

const getCardDependencies = `-- name: GetCardDependencies :many
SELECT kc.card_id, kc.board_id, kc.title, kc.description, kc.status, kc.assignee, kc.story_points, kc.acceptance_criteria, kc.time_spent_hours, kc.created_at, kc.created_by, kc.updated_at, kc.updated_by, kc.priority, kc.type, kc.is_blocked, kc.blocked_reason 
FROM card_dependencies cd JOIN kanban_cards kc ON cd.depends_on_card_id = kc.card_id 
WHERE cd.card_id = $1
`

// Purpose: Retrieve detailed information about all dependency cards for a given card.
// Parameter: $1 = card_id
func (q *Queries) GetCardDependencies(ctx context.Context, cardID int32) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getCardDependencies, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KanbanCard
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.CardID,
			&i.BoardID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Assignee,
			&i.StoryPoints,
			&i.AcceptanceCriteria,
			&i.TimeSpentHours,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Priority,
			&i.Type,
			&i.IsBlocked,
			&i.BlockedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardDependencyIds = `-- name: GetCardDependencyIds :many
SELECT depends_on_card_id FROM card_dependencies WHERE card_id = $1
`

// Purpose: Retrieve all cards that the specified card depends on.
// Parameter: $1 = card_id
func (q *Queries) GetCardDependencyIds(ctx context.Context, cardID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getCardDependencyIds, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var depends_on_card_id int32
		if err := rows.Scan(&depends_on_card_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_card_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKanbanCardById = `-- name: GetKanbanCardById :one
SELECT card_id, board_id, title, description, status, assignee, story_points, acceptance_criteria, time_spent_hours, created_at, created_by, updated_at, updated_by, priority, type, is_blocked, blocked_reason from kanban_cards WHERE card_id = $1
`

func (q *Queries) GetKanbanCardById(ctx context.Context, cardID int32) (KanbanCard, error) {
	row := q.db.QueryRow(ctx, getKanbanCardById, cardID)
	var i KanbanCard
	err := row.Scan(
		&i.CardID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Assignee,
		&i.StoryPoints,
		&i.AcceptanceCriteria,
		&i.TimeSpentHours,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Priority,
		&i.Type,
		&i.IsBlocked,
		&i.BlockedReason,
	)
	return i, err
}

const getKanbanCards = `-- name: GetKanbanCards :many
SELECT card_id, board_id, title, description, status, assignee, story_points, acceptance_criteria, time_spent_hours, created_at, created_by, updated_at, updated_by, priority, type, is_blocked, blocked_reason from kanban_cards
`

func (q *Queries) GetKanbanCards(ctx context.Context) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getKanbanCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KanbanCard
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.CardID,
			&i.BoardID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Assignee,
			&i.StoryPoints,
			&i.AcceptanceCriteria,
			&i.TimeSpentHours,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Priority,
			&i.Type,
			&i.IsBlocked,
			&i.BlockedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKanbanCardsForBoard = `-- name: GetKanbanCardsForBoard :many
SELECT card_id, board_id, title, description, status, assignee, story_points, acceptance_criteria, time_spent_hours, created_at, created_by, updated_at, updated_by, priority, type, is_blocked, blocked_reason from kanban_cards WHERE board_id = $1
`

func (q *Queries) GetKanbanCardsForBoard(ctx context.Context, boardID int32) ([]KanbanCard, error) {
	rows, err := q.db.Query(ctx, getKanbanCardsForBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KanbanCard
	for rows.Next() {
		var i KanbanCard
		if err := rows.Scan(
			&i.CardID,
			&i.BoardID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Assignee,
			&i.StoryPoints,
			&i.AcceptanceCriteria,
			&i.TimeSpentHours,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Priority,
			&i.Type,
			&i.IsBlocked,
			&i.BlockedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kanbanCardExists = `-- name: KanbanCardExists :one
SELECT EXISTS(SELECT 1 FROM kanban_cards WHERE card_id = $1)
`

func (q *Queries) KanbanCardExists(ctx context.Context, cardID int32) (bool, error) {
	row := q.db.QueryRow(ctx, kanbanCardExists, cardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateKanbanCard = `-- name: UpdateKanbanCard :execresult
UPDATE kanban_cards SET title = $2, description = $3, status = $4, assignee = $5, story_points = $6, acceptance_criteria = $7, time_spent_hours = $8,
 priority = $9, type = $10, is_blocked = $11, blocked_reason = $12, updated_at = $13, updated_by = $14 WHERE card_id = $1
`

type UpdateKanbanCardParams struct {
	CardID             int32
	Title              string
	Description        pgtype.Text
	Status             string
	Assignee           pgtype.Text
	StoryPoints        pgtype.Int2
	AcceptanceCriteria pgtype.Text
	TimeSpentHours     pgtype.Numeric
	Priority           pgtype.Text
	Type               pgtype.Text
	IsBlocked          pgtype.Bool
	BlockedReason      pgtype.Text
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.Text
}

func (q *Queries) UpdateKanbanCard(ctx context.Context, arg UpdateKanbanCardParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateKanbanCard,
		arg.CardID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Assignee,
		arg.StoryPoints,
		arg.AcceptanceCriteria,
		arg.TimeSpentHours,
		arg.Priority,
		arg.Type,
		arg.IsBlocked,
		arg.BlockedReason,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
}
