// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban-card-comment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKanbanComment = `-- name: CreateKanbanComment :one
INSERT INTO card_comments (card_id, comment_text, comment_by, created_at) 
VALUES ($1, $2, $3, $4) RETURNING comment_id, card_id, comment_text, comment_by, created_at
`

type CreateKanbanCommentParams struct {
	CardID      int32
	CommentText string
	CommentBy   string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateKanbanComment(ctx context.Context, arg CreateKanbanCommentParams) (CardComment, error) {
	row := q.db.QueryRow(ctx, createKanbanComment,
		arg.CardID,
		arg.CommentText,
		arg.CommentBy,
		arg.CreatedAt,
	)
	var i CardComment
	err := row.Scan(
		&i.CommentID,
		&i.CardID,
		&i.CommentText,
		&i.CommentBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllKanbanComments = `-- name: DeleteAllKanbanComments :exec
DELETE FROM card_comments
`

func (q *Queries) DeleteAllKanbanComments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllKanbanComments)
	return err
}

const deleteKanbanComment = `-- name: DeleteKanbanComment :exec
DELETE FROM card_comments WHERE comment_id = $1
`

func (q *Queries) DeleteKanbanComment(ctx context.Context, commentID int32) error {
	_, err := q.db.Exec(ctx, deleteKanbanComment, commentID)
	return err
}

const deleteKanbanCommentsForCard = `-- name: DeleteKanbanCommentsForCard :exec
DELETE FROM card_comments WHERE card_id = $1
`

func (q *Queries) DeleteKanbanCommentsForCard(ctx context.Context, cardID int32) error {
	_, err := q.db.Exec(ctx, deleteKanbanCommentsForCard, cardID)
	return err
}

const getKanbanCardComments = `-- name: GetKanbanCardComments :many
SELECT comment_id, card_id, comment_text, comment_by, created_at FROM card_comments WHERE card_id = $1
`

func (q *Queries) GetKanbanCardComments(ctx context.Context, cardID int32) ([]CardComment, error) {
	rows, err := q.db.Query(ctx, getKanbanCardComments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardComment
	for rows.Next() {
		var i CardComment
		if err := rows.Scan(
			&i.CommentID,
			&i.CardID,
			&i.CommentText,
			&i.CommentBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKanbanCommentById = `-- name: GetKanbanCommentById :one
SELECT comment_id, card_id, comment_text, comment_by, created_at FROM card_comments WHERE comment_id = $1
`

func (q *Queries) GetKanbanCommentById(ctx context.Context, commentID int32) (CardComment, error) {
	row := q.db.QueryRow(ctx, getKanbanCommentById, commentID)
	var i CardComment
	err := row.Scan(
		&i.CommentID,
		&i.CardID,
		&i.CommentText,
		&i.CommentBy,
		&i.CreatedAt,
	)
	return i, err
}
