// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban-intergration-check.sql

package db

import (
	"context"
)

const boardCardCommentRelationshipExists = `-- name: BoardCardCommentRelationshipExists :one
SELECT EXISTS (
  SELECT 1
  FROM card_comments cmt
  JOIN kanban_cards crd ON cmt.card_id = crd.card_id
  JOIN kanban_boards brd ON crd.board_id = brd.board_id
  WHERE cmt.comment_id = $1 AND crd.card_id = $2 AND brd.board_id = $3
)
`

type BoardCardCommentRelationshipExistsParams struct {
	CommentID int32
	CardID    int32
	BoardID   int32
}

// Check if a comment, card, and board are all related
func (q *Queries) BoardCardCommentRelationshipExists(ctx context.Context, arg BoardCardCommentRelationshipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, boardCardCommentRelationshipExists, arg.CommentID, arg.CardID, arg.BoardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const cardBelongsToBoard = `-- name: CardBelongsToBoard :one
SELECT EXISTS (
  SELECT 1
  FROM kanban_cards
  WHERE card_id = $1 AND board_id = $2
)
`

type CardBelongsToBoardParams struct {
	CardID  int32
	BoardID int32
}

// Check if a card with given card_id belongs to a board with given board_id
func (q *Queries) CardBelongsToBoard(ctx context.Context, arg CardBelongsToBoardParams) (bool, error) {
	row := q.db.QueryRow(ctx, cardBelongsToBoard, arg.CardID, arg.BoardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const commentBelongsToCard = `-- name: CommentBelongsToCard :one
SELECT EXISTS (
  SELECT 1
  FROM card_comments
  WHERE comment_id = $1 AND card_id = $2
)
`

type CommentBelongsToCardParams struct {
	CommentID int32
	CardID    int32
}

// Check if a comment with given comment_id belongs to a card with given card_id
func (q *Queries) CommentBelongsToCard(ctx context.Context, arg CommentBelongsToCardParams) (bool, error) {
	row := q.db.QueryRow(ctx, commentBelongsToCard, arg.CommentID, arg.CardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
