// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: kanban-board.sql

package db

import (
	"context"
)

const getKanbanBoards = `-- name: GetKanbanBoards :many
SELECT board_id, board_name, description, created_at, created_by, updated_at, updated_by from kanban_boards
`

func (q *Queries) GetKanbanBoards(ctx context.Context) ([]KanbanBoard, error) {
	rows, err := q.db.QueryContext(ctx, getKanbanBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KanbanBoard
	for rows.Next() {
		var i KanbanBoard
		if err := rows.Scan(
			&i.BoardID,
			&i.BoardName,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
