// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardAttachment struct {
	AttachmentID   int32
	CardID         int32
	Filename       string
	FileType       pgtype.Text
	FileSizeBytes  pgtype.Int8
	AttachmentData []byte
	UploadedAt     pgtype.Timestamptz
	UploadedBy     string
}

type CardComment struct {
	CommentID   int32
	CardID      int32
	CommentText string
	CommentBy   string
	CreatedAt   pgtype.Timestamptz
}

type CardDependency struct {
	CardID          int32
	DependsOnCardID int32
}

type KanbanBoard struct {
	BoardID     int32
	BoardName   string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.Text
}

type KanbanCard struct {
	CardID             int32
	BoardID            int32
	Title              string
	Description        pgtype.Text
	Status             string
	Assignee           pgtype.Text
	StoryPoints        pgtype.Int2
	AcceptanceCriteria pgtype.Text
	TimeSpentHours     pgtype.Numeric
	CreatedAt          pgtype.Timestamptz
	CreatedBy          string
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.Text
	Priority           pgtype.Text
	Type               pgtype.Text
	IsBlocked          pgtype.Bool
	BlockedReason      pgtype.Text
}
