// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type CardAttachment struct {
	AttachmentID   int32
	CardID         int32
	Filename       string
	FileType       sql.NullString
	FileSizeBytes  sql.NullInt64
	AttachmentData []byte
	UploadedAt     sql.NullTime
	UploadedBy     string
}

type CardComment struct {
	CommentID   int32
	CardID      int32
	CommentText string
	CommentBy   string
	CreatedAt   sql.NullTime
}

type CardDependency struct {
	CardID          int32
	DependsOnCardID int32
}

type KanbanBoard struct {
	BoardID     int32
	BoardName   string
	Description sql.NullString
	CreatedAt   time.Time
	CreatedBy   string
	UpdatedAt   sql.NullTime
	UpdatedBy   sql.NullString
}

type KanbanCard struct {
	CardID             int32
	BoardID            int32
	Title              string
	Description        sql.NullString
	Status             string
	Assignee           sql.NullString
	StoryPoints        sql.NullInt16
	AcceptanceCriteria sql.NullString
	TimeSpentHours     sql.NullString
	CreatedAt          time.Time
	CreatedBy          string
	UpdatedAt          sql.NullTime
	UpdatedBy          sql.NullString
	Priority           sql.NullString
	Type               sql.NullString
	IsBlocked          sql.NullBool
	BlockedReason      sql.NullString
}
